### ISSUE TITLE
Grafana configuration file uses old telemetry parameters

### ISSUE THREAD

**Issue by nickembrey** [oresat/uniclogs-yamcs#18]
The Grafana configuration file (`grafana-dashboard.json`) uses a telemetry parameter format that was changed in af131cce58618b2bf0f1ee56fe0789a6cfaaabdb. The Grafana parameters should be updated to use UpperCamelCase.

**Comment by nickembrey** [comment]
@ryanpdx, there's a parameter in yamcs, `C3TxPLLLock` and a similar parameter that Grafana is looking for but can't find, `C3LTXPLLLock` (previously `C3_L_TX_PLL_Lock`) -- only difference is the extra "L" in Grafana. Are these the same thing? Can I update the Grafana name?

**Comment by ryanpdx** [comment]
Actually that name is wrong in the XTCE and therefor Yamcs. It should be `C3LRxPLLLock`.
