### ISSUE TITLE
Fix: No releases in UniClOGS-Yamcs Releases page

### ISSUE THREAD

**Issue by jiangha4** [oresat/uniclogs-yamcs#52]
For manual install, readme says to Fetch the latest pre-packaged artifacts from the UniClOGS-Yamcs Releases page https://github.com/oresat/uniclogs-yamcs/releases.  

There are no releases on that page.

**Comment by dmitri-mcguckin** [comment]
We could definitely be using tags to mark release-candidates, but if you're talking about the Github Releases page, we don't use it because there's nothing useful to release there.

We build and publish docker images instead and that's how we deploy to production.

**Comment by jiangha4** [comment]
This should be reflected in the README then. All the issues I've raised are directly asked of who ever is trying to onboard to the project. 

`We build and publish docker images instead and that's how we deploy to production.`

Then this should be reflected in the readme. As it stands currently, the dockerfile located in the dist dir does not build correctly. There is no production docker image to pull anywhere and the links on the readme point me to places where the packages don't exist.
